apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskman-deploy
  labels:
    app: taskman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskman
  template:
    metadata:
      labels:
        app: taskman
    spec:
      containers:
      - name: taskman
        image: dntacr888.azurecr.io/taskman
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskman-service
spec:
  selector:
    app: taskman
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080        